a=int(input("Enter the value of a "))
b=int(input("Enter the value of b "))
c=a+b
print("The value of C=",c)
a=int(input("Enter the value of a "))
b=int(input("Enter the value of b "))
c=a-b
print("The value of C=",c)
a=int(input("Enter the value of a "))
b=int(input("Enter the value of b "))
c=a*b
print("The value of C=",c)
a=float(input("Enter the value of a "))
b=int(input("Enter the value of b "))
c=a/b
print("The value of C=",c)
